/**
 * ─────────────────────────────────────────────────────────────────────────────
 * App state, backed by the database.
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * This file used to be the whole persistence layer: influencers serialised into
 * device storage, one key per record, an index key listing the ids, and a
 * migration that reconciled the two when a quota error left them disagreeing.
 * That is all gone. Rows live in Postgres, files live in S3, and both are
 * scoped to the signed-in user by Row Level Security.
 *
 * ── What changed for callers ─────────────────────────────────────────────────
 *
 * `useInfluencers()` still returns `[influencers, setInfluencers]`, so the
 * screens read the same way they always did. But the setter is no longer a
 * plain state setter — a write has to reach the server, and the server is the
 * thing that can fail. So alongside it there are explicit operations:
 *
 *     const { influencers, updateInfluencer, addInfluencer, removeInfluencer }
 *
 * Prefer those. The array-setter shim exists so the migration did not have to
 * rewrite every screen at once; it applies the change locally and pushes a
 * patch, and it cannot express a delete.
 *
 * ── Optimistic, with a real rollback ─────────────────────────────────────────
 *
 * Edits apply to local state immediately and reconcile with the server's
 * response. A failed write restores the previous value rather than leaving the
 * UI showing something that was never saved — the old local-first code could
 * not get this wrong because the write always "succeeded"; over a network it is
 * the main way state and truth drift apart.
 */

import { createContext, useContext, useCallback, useEffect, useMemo, useRef, useState } from 'react'

import * as influencerRepo from './data/influencers'
import * as generationRepo from './data/generations'
import { clearUrlCache, resolveUrls, URL_REFRESH_WINDOW_MS } from './data/assets'
import { useAuth } from './auth/AuthContext'
import { userMessage } from './errors'

const InfluencersCtx = createContext(null)
const BrandDealsCtx = createContext(null)

/**
 * Local ids for things that have not been saved yet.
 *
 * Database ids are UUIDs generated by Postgres. This is only for transient
 * client-side keys — a React list key before the row exists — and must never be
 * written as a primary key.
 */
export function generateId() {
  return Date.now().toString(36) + Math.random().toString(36).slice(2)
}

export function StoreProvider({ children }) {
  const { userId, isSignedIn } = useAuth()

  const [influencers, setInfluencersState] = useState([])
  const [loading, setLoading] = useState(false)
  // Which user's roster has finished loading at least once. Until it has,
  // `loading` reads true — otherwise the first render after sign-in showed an
  // empty roster ("No influencers yet") for the moment before the fetch began.
  const [loadedFor, setLoadedFor] = useState(null)
  const [error, setError] = useState(null)

  const alive = useRef(true)
  useEffect(() => () => { alive.current = false }, [])

  // The latest roster, for callbacks that must keep a stable identity.
  const influencersRef = useRef(influencers)
  useEffect(() => { influencersRef.current = influencers }, [influencers])

  // Per influencer, the number of the newest edit sent. A save's response is
  // only applied if no newer edit has been made since — see updateInfluencer.
  const editSeq = useRef(new Map())

  // Files deleted from a gallery this session. A change notification that was
  // already on its way can still describe the job that made one as collected;
  // without this, adopting it put the entry just deleted back on screen.
  const removedAssets = useRef(new Set())

  /** Reload the roster from the server. */
  const refresh = useCallback(async () => {
    if (!isSignedIn) { setInfluencersState([]); return }

    setLoading(true)
    setError(null)
    try {
      const rows = await influencerRepo.list()
      if (alive.current) setInfluencersState(rows)
    } catch (e) {
      if (alive.current) setError(userMessage(e, 'Unable to load your influencers. Please try again.'))
      console.warn('[store] load failed:', e?.message ?? e)
    } finally {
      if (alive.current) { setLoading(false); setLoadedFor(userId) }
    }
  }, [isSignedIn, userId])

  // Reload whenever the signed-in user changes.
  //
  // Clearing on sign-out is not cosmetic: without it the next person to sign in
  // on this device sees the previous user's roster until the fetch returns, and
  // the cached signed URLs would still resolve for a few minutes.
  useEffect(() => {
    removedAssets.current.clear()
    if (!userId) {
      setInfluencersState([])
      clearUrlCache()
      return
    }
    refresh()
  }, [userId, refresh])

  /**
   * Re-sign URLs that are close to expiring.
   *
   * Every image and video field holds a presigned URL that dies ten minutes
   * after it was signed, and the roster used to be resolved once, at load —
   * leave the app open past that and every tile broke, and those same dead
   * URLs were what generation sent to KIE. The app calls this on a timer and on
   * returning to the foreground. Only URLs inside the refresh window change, so
   * a record whose links are still good keeps its identity.
   */
  const refreshUrls = useCallback(async () => {
    const ids = influencersRef.current.flatMap(influencerRepo.assetIdsOf)
    if (!ids.length) return

    const urls = await resolveUrls(ids, { minRemainingMs: URL_REFRESH_WINDOW_MS })
    if (!alive.current || urls.size === 0) return

    setInfluencersState(prev => {
      let changed = false
      const next = prev.map(record => {
        const fresh = influencerRepo.withUrls(record, urls)
        if (fresh !== record) changed = true
        return fresh
      })
      return changed ? next : prev
    })
  }, [])

  // ── Operations ─────────────────────────────────────────────────────────────

  const addInfluencer = useCallback(async (record, options) => {
    const created = await influencerRepo.create(record, options)
    if (alive.current) setInfluencersState(prev => [created, ...prev])
    return created
  }, [])

  const updateInfluencer = useCallback(async (id, patch) => {
    const previous = influencersRef.current.find(i => i.id === id)
    const seq = (editSeq.current.get(id) || 0) + 1
    editSeq.current.set(id, seq)
    // Responses can arrive out of order. Applying an older one on top of a newer
    // edit put back text the user had already changed, mid-typing.
    const isNewest = () => editSeq.current.get(id) === seq

    // Optimistic: the UI moves now, the server catches up.
    setInfluencersState(prev => prev.map(i => (i.id === id ? { ...i, ...patch } : i)))

    try {
      const saved = await influencerRepo.update(id, patch)
      if (!saved || !alive.current || !isNewest()) return saved
      // Merge rather than replace: `saved` has no generationHistory (the update
      // does not re-query it) and overwriting would empty the gallery on screen.
      setInfluencersState(prev => prev.map(i => (i.id === id ? { ...i, ...saved, generationHistory: i.generationHistory } : i)))
      return saved
    } catch (e) {
      if (alive.current && previous && isNewest()) {
        setInfluencersState(prev => prev.map(i => (i.id === id ? previous : i)))
      }
      throw e
    }
  }, [])

  const removeInfluencer = useCallback(async id => {
    const snapshot = influencers
    setInfluencersState(prev => prev.filter(i => i.id !== id))
    try {
      await influencerRepo.remove(id)
    } catch (e) {
      if (alive.current) setInfluencersState(snapshot)
      throw e
    }
  }, [influencers])

  /** Put an entry at the front of an influencer's gallery, at most once. */
  const showInGallery = useCallback((influencerId, entry) => {
    if (entry?.assetId && removedAssets.current.has(String(entry.assetId))) return
    setInfluencersState(prev => prev.map(i =>
      i.id === influencerId && !(i.generationHistory || []).some(g => g.id === entry.id)
        ? { ...i, generationHistory: [entry, ...(i.generationHistory || [])] }
        : i))
  }, [])

  /** Append a finished generation to an influencer's gallery. */
  const addGeneration = useCallback(async ({ influencerId, assetId, kind, label }) => {
    const entry = await generationRepo.add({ influencerId, assetId, kind, label })
    if (alive.current) showInGallery(influencerId, entry)
    return entry
  }, [showInGallery])

  /**
   * Show a result someone else filed — the server's worker collecting a job
   * after the app stopped watching it. Without this it would only appear after
   * the next full reload.
   *
   * @returns {Promise<boolean>} false while the gallery row does not exist yet
   */
  const adoptGeneration = useCallback(async ({ influencerId, assetId }) => {
    const entry = await generationRepo.findByAsset(assetId)
    if (!entry) return false
    if (alive.current) showInGallery(influencerId, entry)
    return true
  }, [showInGallery])

  const removeGeneration = useCallback(async (influencerId, generationId) => {
    const snapshot = influencers
    const removedAssetId = influencersRef.current
      .find(i => i.id === influencerId)?.generationHistory
      ?.find(g => g.id === generationId)?.assetId
    if (removedAssetId) removedAssets.current.add(String(removedAssetId))
    setInfluencersState(prev => prev.map(i => {
      if (i.id !== influencerId) return i
      const entry = (i.generationHistory || []).find(g => g.id === generationId)
      const next = { ...i, generationHistory: (i.generationHistory || []).filter(g => g.id !== generationId) }
      // The file may also be a reference sheet or the main image. The database
      // clears those fields itself; this stops the screen — and the next video
      // request — from using a link to a file that no longer exists.
      return entry?.assetId ? influencerRepo.withoutAsset(next, entry.assetId) : next
    }))
    try {
      await generationRepo.remove(generationId)
    } catch (e) {
      if (removedAssetId) removedAssets.current.delete(String(removedAssetId))
      if (alive.current) setInfluencersState(snapshot)
      throw e
    }
  }, [influencers])

  /**
   * The `setInfluencers(prev => next)` shim.
   *
   * Screens written against local-first state call this with a mapper. It
   * diffs the result and pushes a patch for whichever record changed.
   *
   * Deliberately limited: it cannot create or delete, because a diff cannot
   * tell "deleted" from "not loaded yet", and guessing would delete a user's
   * work. Callers that add or remove must use the explicit operations.
   */
  const setInfluencers = useCallback(updater => {
    setInfluencersState(prev => {
      const next = typeof updater === 'function' ? updater(prev) : updater

      for (const record of next) {
        const before = prev.find(i => i.id === record.id)
        if (!before || before === record) continue

        const patch = {}
        for (const key of Object.keys(record)) {
          // generationHistory is server-owned; it is written through
          // addGeneration, never by patching the influencer.
          if (key === 'generationHistory') continue
          if (record[key] !== before[key]) patch[key] = record[key]
        }

        if (Object.keys(patch).length > 0) {
          influencerRepo.update(record.id, patch).catch(e => {
            console.warn('[store] background update failed:', e?.message ?? e)
            // Re-read rather than guess at a rollback: another field may have
            // changed in the same tick and the server is the arbiter.
            refresh()
          })
        }
      }

      return next
    })
  }, [refresh])

  const influencersValue = useMemo(
    () => Object.assign([influencers, setInfluencers], {
      influencers,
      loading: loading || (!!userId && loadedFor !== userId),
      error,
      refresh,
      refreshUrls,
      addInfluencer,
      updateInfluencer,
      removeInfluencer,
      addGeneration,
      adoptGeneration,
      removeGeneration,
    }),
    [influencers, setInfluencers, loading, loadedFor, userId, error, refresh, refreshUrls,
     addInfluencer, updateInfluencer, removeInfluencer, addGeneration, adoptGeneration, removeGeneration],
  )

  // Brand deals are not yet wired to a screen on mobile. The context stays so
  // the web app's import keeps resolving; the table and policies exist.
  const brandDealsValue = useMemo(() => [[], () => {}], [])

  return (
    <InfluencersCtx.Provider value={influencersValue}>
      <BrandDealsCtx.Provider value={brandDealsValue}>
        {children}
      </BrandDealsCtx.Provider>
    </InfluencersCtx.Provider>
  )
}

/**
 * @returns {[Array, Function] & {
 *   influencers: Array, loading: boolean, error: string|null, refresh: Function, refreshUrls: Function,
 *   addInfluencer: Function, updateInfluencer: Function, removeInfluencer: Function,
 *   addGeneration: Function, adoptGeneration: Function, removeGeneration: Function
 * }}
 */
export function useInfluencers() {
  const ctx = useContext(InfluencersCtx)
  if (!ctx) throw new Error('useInfluencers must be used inside <StoreProvider>')
  return ctx
}

export function useBrandDeals() {
  return useContext(BrandDealsCtx)
}
